---
galaxy_info:
  author: parmstro
  description: Retrieve event logs from multiple AMT systems in parallel
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - intel
    - amt
    - events
    - logs
    - monitoring

dependencies: []
