---
galaxy_info:
  author: parmstro
  description: Fleet status monitoring for Intel AMT systems
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - intel
    - amt
    - fleet
    - monitoring
    - status

dependencies: []
