#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026
# GNU General Public License v3.0 or later (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: amt_tls_config
short_description: Configure TLS/HTTPS settings and certificates for Intel AMT
version_added: "1.0.0"
description:
    - Enable or disable HTTPS on Intel AMT management interface.
    - Upload TLS certificates to AMT for secure connections.
    - Integrates with Red Hat IDM (IPA) via certmonger for certificate generation.
    - Supports manual certificate upload from PEM files.
    - Configures TLS port settings (16992 HTTP, 16993 HTTPS).
options:
    host:
        description:
            - Hostname or IP address of the AMT management interface.
        required: true
        type: str
    username:
        description:
            - AMT admin username.
        required: true
        type: str
    password:
        description:
            - AMT admin password.
        required: true
        type: str
        no_log: true
    port:
        description:
            - AMT management port for this configuration operation.
            - Use 16992 for HTTP, 16993 for HTTPS.
        required: false
        type: int
        default: 16992
    use_tls:
        description:
            - Whether to use TLS for THIS configuration connection.
            - Set to false when connecting via HTTP to enable HTTPS.
        required: false
        type: bool
        default: false
    verify_ssl:
        description:
            - Whether to verify SSL certificates for this connection.
        required: false
        type: bool
        default: false
    tls_enabled:
        description:
            - Enable or disable HTTPS on AMT.
            - When true, AMT will accept connections on port 16993.
            - When false, only HTTP on port 16992 is available.
        required: false
        type: bool
    certificate_path:
        description:
            - Path to PEM-encoded certificate file to upload to AMT.
            - Can be a certificate generated by certmonger/IPA.
            - File must contain the full certificate chain if needed.
        required: false
        type: path
    private_key_path:
        description:
            - Path to PEM-encoded private key file.
            - Required when certificate_path is provided.
        required: false
        type: path
        no_log: true
    ca_certificate_path:
        description:
            - Path to PEM-encoded CA certificate file.
            - Used to establish trust chain for the AMT certificate.
        required: false
        type: path
    certmonger_request:
        description:
            - Request a new certificate via certmonger/IPA before upload.
            - If true, module will use ipa-getcert to request certificate.
        required: false
        type: bool
        default: false
    certmonger_nickname:
        description:
            - Nickname for certmonger certificate request.
            - Used as identifier in certmonger tracking.
        required: false
        type: str
    certmonger_subject:
        description:
            - Subject DN for certificate request.
            - Example C(CN=nuc01.amt.example.com,O=Example Org).
        required: false
        type: str
    certmonger_principal:
        description:
            - Kerberos principal for IPA certificate request.
            - Example C(host/nuc01.amt.example.com@EXAMPLE.COM).
        required: false
        type: str
    http_port:
        description:
            - HTTP port number (non-TLS).
            - Change only if you need non-standard port configuration.
        required: false
        type: int
        default: 16992
    https_port:
        description:
            - HTTPS port number (TLS).
            - Change only if you need non-standard port configuration.
        required: false
        type: int
        default: 16993
author:
    - parmstro
notes:
    - After enabling HTTPS, subsequent connections should use port 16993 with use_tls=true.
    - Certificate must match the AMT hostname for proper SSL verification.
    - Private key must not be password-protected.
    - Certmonger integration requires ipa-getcert command (Red Hat IPA client).
    - When using certmonger_request, certificate files are created automatically.
    - AMT may require reboot for TLS configuration changes to fully take effect.
    - Always test connectivity after enabling HTTPS before disconnecting HTTP.
'''

EXAMPLES = r'''
# Enable HTTPS on AMT with existing certificate
- name: Upload certificate and enable HTTPS
  parmstro.intel_amt.amt_tls_config:
    host: nuc01.amt.example.com
    username: admin
    password: "{{ amt_password }}"
    port: 16992
    use_tls: false
    tls_enabled: true
    certificate_path: /etc/pki/amt/nuc01.crt
    private_key_path: /etc/pki/amt/nuc01.key
    ca_certificate_path: /etc/pki/ca-trust/source/anchors/ipa-ca.crt

# Request certificate from Red Hat IPA via certmonger and upload
- name: Request certificate from IPA and configure HTTPS
  parmstro.intel_amt.amt_tls_config:
    host: c1s2n2.amt.example.com
    username: admin
    password: "{{ amt_password }}"
    port: 16992
    use_tls: false
    tls_enabled: true
    certmonger_request: true
    certmonger_nickname: "amt-c1s2n2"
    certmonger_subject: "CN=c1s2n2.amt.example.com"
    certmonger_principal: "host/c1s2n2.amt.example.com@EXAMPLE.COM"
    certificate_path: /var/lib/certmonger/amt/c1s2n2.crt
    private_key_path: /var/lib/certmonger/amt/c1s2n2.key

# Disable HTTPS (revert to HTTP only)
- name: Disable HTTPS on AMT
  parmstro.intel_amt.amt_tls_config:
    host: nuc01.amt.example.com
    username: admin
    password: "{{ amt_password }}"
    port: 16993
    use_tls: true
    tls_enabled: false

# Upload certificate without changing TLS state
- name: Update AMT certificate
  parmstro.intel_amt.amt_tls_config:
    host: nuc01.amt.example.com
    username: admin
    password: "{{ amt_password }}"
    port: 16993
    use_tls: true
    certificate_path: /etc/pki/amt/nuc01-renewed.crt
    private_key_path: /etc/pki/amt/nuc01-renewed.key

# Configure custom ports
- name: Configure non-standard HTTPS port
  parmstro.intel_amt.amt_tls_config:
    host: nuc01.amt.example.com
    username: admin
    password: "{{ amt_password }}"
    port: 16992
    use_tls: false
    tls_enabled: true
    http_port: 16992
    https_port: 8443
    certificate_path: /etc/pki/amt/nuc01.crt
    private_key_path: /etc/pki/amt/nuc01.key
'''

RETURN = r'''
changed:
    description: Whether configuration was changed
    returned: always
    type: bool
    sample: true
tls_enabled:
    description: Current TLS enabled status
    returned: always
    type: bool
    sample: true
certificate_uploaded:
    description: Whether a certificate was uploaded
    returned: always
    type: bool
    sample: true
certmonger_request_id:
    description: Certmonger request tracking ID
    returned: when certmonger_request is true
    type: str
    sample: "20260530120000"
https_port:
    description: HTTPS port number
    returned: always
    type: int
    sample: 16993
http_port:
    description: HTTP port number
    returned: always
    type: int
    sample: 16992
msg:
    description: Human-readable message about the operation
    returned: always
    type: str
    sample: "TLS enabled and certificate uploaded successfully"
'''

from ansible.module_utils.basic import AnsibleModule
import requests
from requests.auth import HTTPDigestAuth
from lxml import etree
import urllib3
import os
import subprocess
import base64

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


class WSMANClient:
    """WS-Management client for Intel AMT"""

    def __init__(self, host, username, password, port=16992, use_tls=False, verify_ssl=False):
        self.host = host
        self.username = username
        self.password = password
        self.port = port
        self.use_tls = use_tls
        self.verify_ssl = verify_ssl
        self.base_url = f"{'https' if use_tls else 'http'}://{host}:{port}/wsman"
        self.auth = HTTPDigestAuth(username, password)

    def _create_envelope(self, action, resource_uri, body=None, selector_set=None):
        """Create SOAP envelope for WSMAN request"""
        SOAP_NS = 'http://www.w3.org/2003/05/soap-envelope'
        WSA_NS = 'http://schemas.xmlsoap.org/ws/2004/08/addressing'
        WSMAN_NS = 'http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd'

        envelope = etree.Element(
            f'{{{SOAP_NS}}}Envelope',
            nsmap={'s': SOAP_NS,
                   'a': WSA_NS,
                   'w': WSMAN_NS}
        )

        header = etree.SubElement(envelope, f'{{{SOAP_NS}}}Header')

        action_elem = etree.SubElement(header, f'{{{WSA_NS}}}Action',
                                       {f'{{{SOAP_NS}}}mustUnderstand': 'true'})
        action_elem.text = action

        to_elem = etree.SubElement(header, f'{{{WSA_NS}}}To',
                                   {f'{{{SOAP_NS}}}mustUnderstand': 'true'})
        to_elem.text = self.base_url

        resource_elem = etree.SubElement(header, f'{{{WSMAN_NS}}}ResourceURI',
                                        {f'{{{SOAP_NS}}}mustUnderstand': 'true'})
        resource_elem.text = resource_uri

        msg_id = etree.SubElement(header, f'{{{WSA_NS}}}MessageID',
                                 {f'{{{SOAP_NS}}}mustUnderstand': 'true'})
        msg_id.text = 'uuid:00000000-8086-8086-8086-000000000001'

        reply_to = etree.SubElement(header, f'{{{WSA_NS}}}ReplyTo')
        address = etree.SubElement(reply_to, f'{{{WSA_NS}}}Address')
        address.text = 'http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous'

        if selector_set:
            sel_set = etree.SubElement(header, f'{{{WSMAN_NS}}}SelectorSet')
            for name, value in selector_set.items():
                selector = etree.SubElement(sel_set, f'{{{WSMAN_NS}}}Selector', Name=name)
                selector.text = value

        body_elem = etree.SubElement(envelope, f'{{{SOAP_NS}}}Body')
        if body is not None:
            body_elem.append(body)

        return envelope

    def _send_request(self, envelope):
        """Send WSMAN request and return response"""
        xml_data = etree.tostring(envelope, encoding='utf-8', xml_declaration=True)

        headers = {
            'Content-Type': 'application/soap+xml;charset=UTF-8',
        }

        try:
            response = requests.post(
                self.base_url,
                data=xml_data,
                headers=headers,
                auth=self.auth,
                verify=self.verify_ssl,
                timeout=30
            )
            response.raise_for_status()
            return etree.fromstring(response.content)
        except requests.exceptions.RequestException as e:
            raise Exception(f"WSMAN request failed: {str(e)}")

    def upload_certificate(self, certificate_data, private_key_data):
        """Upload certificate and private key to AMT"""
        # AMT certificate upload via AMT_PublicKeyCertificate and AMT_PublicPrivateKeyPair
        # This is a placeholder - actual implementation depends on AMT 10.0.56 capabilities
        AMT_NS = 'http://intel.com/wbem/wscim/1/amt-schema/1/AMT_PublicKeyManagementService'
        resource_uri = AMT_NS
        action = f'{AMT_NS}/AddCertificate'

        # Combine certificate and key for AMT (PKCS#12 or PEM format)
        # This needs to be base64 encoded
        cert_b64 = base64.b64encode(certificate_data.encode()).decode()
        key_b64 = base64.b64encode(private_key_data.encode()).decode()

        body = etree.Element(
            f'{{{AMT_NS}}}AddCertificate_INPUT',
            nsmap={'amt': AMT_NS}
        )

        cert_elem = etree.SubElement(body, f'{{{AMT_NS}}}CertificateBlob')
        cert_elem.text = cert_b64

        envelope = self._create_envelope(action, resource_uri, body)
        response = self._send_request(envelope)
        return response

    def configure_tls_settings(self, tls_enabled, http_port=16992, https_port=16993):
        """Configure TLS/HTTPS settings on AMT"""
        # Configure AMT_TLSSettingData or similar
        # This configures which ports are enabled and TLS mode
        AMT_NS = 'http://intel.com/wbem/wscim/1/amt-schema/1/AMT_TLSSettingData'
        resource_uri = AMT_NS
        action = 'http://schemas.xmlsoap.org/ws/2004/09/transfer/Put'

        selector_set = {'InstanceID': 'Intel(r) AMT TLS Settings'}

        body = etree.Element(
            f'{{{AMT_NS}}}AMT_TLSSettingData',
            nsmap={'amt': AMT_NS}
        )

        enabled_elem = etree.SubElement(body, f'{{{AMT_NS}}}Enabled')
        enabled_elem.text = 'true' if tls_enabled else 'false'

        envelope = self._create_envelope(action, resource_uri, body, selector_set)
        response = self._send_request(envelope)
        return response


def request_certificate_certmonger(module, nickname, subject, principal, cert_path, key_path):
    """Request certificate from IPA via certmonger"""
    if not os.path.exists('/usr/bin/ipa-getcert'):
        module.fail_json(msg="ipa-getcert not found. Install ipa-client package.")

    # Ensure directories exist
    cert_dir = os.path.dirname(cert_path)
    key_dir = os.path.dirname(key_path)

    if cert_dir and not os.path.exists(cert_dir):
        os.makedirs(cert_dir, mode=0o755)
    if key_dir and not os.path.exists(key_dir):
        os.makedirs(key_dir, mode=0o755)

    # Check if certificate already exists and is being tracked
    check_cmd = ['ipa-getcert', 'list', '-n', nickname]
    result = subprocess.run(check_cmd, capture_output=True, text=True)

    if result.returncode == 0 and 'status: MONITORING' in result.stdout:
        # Certificate already exists and is valid
        return {'changed': False, 'request_id': nickname, 'msg': 'Certificate already exists and is valid'}

    # Request new certificate
    cmd = [
        'ipa-getcert', 'request',
        '-n', nickname,
        '-f', cert_path,
        '-k', key_path,
    ]

    if subject:
        cmd.extend(['-N', subject])

    if principal:
        cmd.extend(['-K', principal])

    # Run certmonger request
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        module.fail_json(msg=f"certmonger request failed: {result.stderr}")

    # Wait for certificate to be issued (with timeout)
    wait_cmd = ['ipa-getcert', 'list', '-n', nickname]
    max_attempts = 30
    attempt = 0

    while attempt < max_attempts:
        result = subprocess.run(wait_cmd, capture_output=True, text=True)
        if 'status: MONITORING' in result.stdout:
            break
        attempt += 1
        import time
        time.sleep(2)

    if attempt >= max_attempts:
        module.fail_json(msg="Timeout waiting for certificate issuance")

    return {'changed': True, 'request_id': nickname, 'msg': 'Certificate requested and issued successfully'}


def run_module():
    module_args = dict(
        host=dict(type='str', required=True),
        username=dict(type='str', required=True),
        password=dict(type='str', required=True, no_log=True),
        port=dict(type='int', required=False, default=16992),
        use_tls=dict(type='bool', required=False, default=False),
        verify_ssl=dict(type='bool', required=False, default=False),
        tls_enabled=dict(type='bool', required=False),
        certificate_path=dict(type='path', required=False),
        private_key_path=dict(type='path', required=False, no_log=True),
        ca_certificate_path=dict(type='path', required=False),
        certmonger_request=dict(type='bool', required=False, default=False),
        certmonger_nickname=dict(type='str', required=False),
        certmonger_subject=dict(type='str', required=False),
        certmonger_principal=dict(type='str', required=False),
        http_port=dict(type='int', required=False, default=16992),
        https_port=dict(type='int', required=False, default=16993),
    )

    result = dict(
        changed=False,
        tls_enabled=False,
        certificate_uploaded=False,
        http_port=16992,
        https_port=16993,
        msg=''
    )

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
        required_together=[
            ['certificate_path', 'private_key_path'],
        ],
        required_if=[
            ['certmonger_request', True, ['certmonger_nickname', 'certificate_path', 'private_key_path']],
        ],
    )

    try:
        # Handle certmonger request if needed
        if module.params['certmonger_request']:
            cert_result = request_certificate_certmonger(
                module,
                module.params['certmonger_nickname'],
                module.params.get('certmonger_subject'),
                module.params.get('certmonger_principal'),
                module.params['certificate_path'],
                module.params['private_key_path']
            )
            result['certmonger_request_id'] = cert_result['request_id']
            result['changed'] = cert_result['changed']

        # Read certificate and key files if provided
        certificate_data = None
        private_key_data = None

        if module.params['certificate_path']:
            if not os.path.exists(module.params['certificate_path']):
                module.fail_json(msg=f"Certificate file not found: {module.params['certificate_path']}")

            with open(module.params['certificate_path'], 'r') as f:
                certificate_data = f.read()

        if module.params['private_key_path']:
            if not os.path.exists(module.params['private_key_path']):
                module.fail_json(msg=f"Private key file not found: {module.params['private_key_path']}")

            with open(module.params['private_key_path'], 'r') as f:
                private_key_data = f.read()

        # Create WSMAN client
        client = WSMANClient(
            host=module.params['host'],
            username=module.params['username'],
            password=module.params['password'],
            port=module.params['port'],
            use_tls=module.params['use_tls'],
            verify_ssl=module.params['verify_ssl']
        )

        messages = []

        # Upload certificate if provided
        if certificate_data and private_key_data and not module.check_mode:
            try:
                client.upload_certificate(certificate_data, private_key_data)
                result['certificate_uploaded'] = True
                result['changed'] = True
                messages.append("Certificate uploaded successfully")
            except Exception as e:
                # AMT 10.0.56 may not support this operation via WSMAN
                # Log warning but don't fail
                messages.append(f"Certificate upload not supported via WSMAN: {str(e)}")
                messages.append("Manual certificate upload may be required via Intel MEBx or web interface")

        # Configure TLS settings if specified
        if module.params['tls_enabled'] is not None and not module.check_mode:
            try:
                client.configure_tls_settings(
                    module.params['tls_enabled'],
                    module.params['http_port'],
                    module.params['https_port']
                )
                result['tls_enabled'] = module.params['tls_enabled']
                result['http_port'] = module.params['http_port']
                result['https_port'] = module.params['https_port']
                result['changed'] = True
                messages.append(f"TLS {'enabled' if module.params['tls_enabled'] else 'disabled'}")
            except Exception as e:
                messages.append(f"TLS configuration not supported via WSMAN: {str(e)}")
                messages.append("Manual TLS configuration may be required via Intel MEBx or web interface")

        result['msg'] = '; '.join(messages) if messages else 'No changes made'

        # Note about AMT 10.0.56 limitations
        if not result['certificate_uploaded'] and certificate_data:
            result['warnings'] = [
                "Intel AMT 10.0.56 has limited WSMAN certificate management support.",
                "You may need to configure certificates via:",
                "1. Intel MEBx (BIOS setup during boot - Ctrl+P)",
                "2. AMT web interface (if already configured)",
                "3. Intel manageability commander tool",
                "This module prepared the certificate files for manual configuration."
            ]

        module.exit_json(**result)

    except Exception as e:
        module.fail_json(msg=str(e), **result)


def main():
    run_module()


if __name__ == '__main__':
    main()
